export type MakerWorldParameterGroupId =
  | "box"
  | "trays"
  | "vertical-dividers"
  | "horizontal-dividers";

export interface MakerWorldParameter {
  /** Exact editable parameter name shown in MakerWorld. */
  name: string;

  /** Rounded numeric value to enter in MakerWorld. */
  value: number;

  /** Preformatted display value generated by the MakerWorld adapter. */
  displayValue: string;

  unit?: "mm";
}

export interface MakerWorldParameterGroup {
  id: MakerWorldParameterGroupId;
  title: string;
  parameters: MakerWorldParameter[];
}

/**
 * Complete presentation model for manual MakerWorld parameter entry.
 *
 * The preview consumes this interface without access to CalculationResult.
 */
export interface MakerWorldParameters {
  groups: MakerWorldParameterGroup[];
  warnings: string[];
}
