import type { CalculationResult } from "@/lib/engineering/types";

type CalculationPreviewProps = {
  result: CalculationResult;
};

type DimensionRowProps = {
  label: string;
  value: number | null;
  unit?: string;
};

function formatDimension(value: number) {
  return Number.isInteger(value)
    ? value.toString()
    : value.toFixed(3).replace(/\.?0+$/, "");
}

function DimensionRow({ label, value, unit = "mm" }: DimensionRowProps) {
  return (
    <div className="flex items-start justify-between gap-6 border-b border-neutral-200 py-3 last:border-b-0">
      <dt className="text-sm text-neutral-600">{label}</dt>

      <dd className="text-right text-sm font-medium tabular-nums text-neutral-900">
        {value === null ? (
          <span className="font-normal text-neutral-400">
            Not yet available
          </span>
        ) : (
          <>
            {formatDimension(value)} {unit}
          </>
        )}
      </dd>
    </div>
  );
}

type ResultSectionProps = {
  title: string;
  children: React.ReactNode;
};

function ResultSection({ title, children }: ResultSectionProps) {
  return (
    <section className="rounded-xl border border-neutral-200 bg-white p-5">
      <h3 className="text-sm font-semibold uppercase tracking-wide text-neutral-500">
        {title}
      </h3>

      <dl className="mt-3">{children}</dl>
    </section>
  );
}

export default function CalculationPreview({
  result,
}: CalculationPreviewProps) {
  const hasGrid =
    result.compartment !== null &&
    result.rows !== null &&
    result.columns !== null;

  return (
    <section className="space-y-6 border-t border-neutral-200 pt-12">
      <header>
        <p className="text-sm font-semibold uppercase tracking-widest text-neutral-500">
          Engineering result
        </p>

        <h2 className="mt-2 text-3xl font-semibold tracking-tight text-neutral-900">
          Calculation Preview
        </h2>

        <p className="mt-3 max-w-2xl leading-7 text-neutral-600">
          These dimensions were generated by the validated Engineering
          Calculation Engine. Height calculations are not yet included in the
          engineering result.
        </p>
      </header>

      <div className="grid gap-6 lg:grid-cols-2">
        <ResultSection title="Box">
          <DimensionRow label="Outside width" value={result.box.outsideWidth} />

          <DimensionRow label="Outside depth" value={result.box.outsideDepth} />

          <DimensionRow label="Inside width" value={result.box.insideWidth} />

          <DimensionRow label="Inside depth" value={result.box.insideDepth} />
        </ResultSection>

        {result.tray && (
          <ResultSection title="Tray">
            <DimensionRow
              label="Outside width"
              value={result.tray.outsideWidth}
            />

            <DimensionRow
              label="Outside depth"
              value={result.tray.outsideDepth}
            />

            <DimensionRow
              label="Usable width"
              value={result.tray.usableWidth}
            />

            <DimensionRow
              label="Usable depth"
              value={result.tray.usableDepth}
            />
          </ResultSection>
        )}

        {hasGrid && result.compartment && (
          <ResultSection title="Equal Grid">
            <DimensionRow label="Rows" value={result.rows} unit="" />

            <DimensionRow label="Columns" value={result.columns} unit="" />

            <DimensionRow
              label="Compartment width"
              value={result.compartment.width}
            />

            <DimensionRow
              label="Compartment depth"
              value={result.compartment.depth}
            />
          </ResultSection>
        )}

        <ResultSection title="Configuration">
          <DimensionRow
            label="Number of trays"
            value={result.trayNumber}
            unit=""
          />

          <div className="flex items-start justify-between gap-6 border-b border-neutral-200 py-3 last:border-b-0">
            <dt className="text-sm text-neutral-600">Calculation strategy</dt>

            <dd className="text-right text-sm font-medium text-neutral-900">
              {result.strategy === "outside-led"
                ? "Overall Outside Size"
                : "Required Usable Space"}
            </dd>
          </div>
        </ResultSection>
      </div>

      <div className="rounded-xl border border-neutral-200 bg-neutral-50 p-5">
        <div className="flex items-start gap-3">
          <span
            className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-neutral-900 text-sm font-semibold text-white"
            aria-hidden="true"
          >
            ✓
          </span>

          <div>
            <h3 className="font-semibold text-neutral-900">
              Validated engineering model
            </h3>

            <p className="mt-1 text-sm leading-6 text-neutral-600">
              Width and depth calculations have been validated against Fusion
              Version 6 – Design Assistant aligned.
            </p>
          </div>
        </div>
      </div>

      {result.warnings.length > 0 && (
        <section className="rounded-xl border border-amber-200 bg-amber-50 p-5">
          <h3 className="font-semibold text-amber-950">Engineering notes</h3>

          <ul className="mt-3 space-y-2 text-sm leading-6 text-amber-900">
            {result.warnings.map((warning) => (
              <li key={warning}>{warning}</li>
            ))}
          </ul>
        </section>
      )}
    </section>
  );
}
